### ISSUE TITLE
Meeting 18.04. - 12:00 Uhr - H.1.5

### ISSUE THREAD

**Issue by modellking** [simonHJanssen/MoDMX#13]
## Tagesplan ##
 - Feature Liste erstellen
 - Lastenheft
 - H.1.5 Einführung
 - Projektmanagement tool ? Git ?
 - UI sketch optimieren

## Vorbereitung ##
 - Benni: Lastenheft für Markdown
 - Jeder: Feature Liste
 - Benni: Projektmanagement tool

 

 comment decisions or issues or anything below during the meeting

**Comment by H7orst** [comment]
Fürs Lastenheft gibt's online Konverter von word nach markdown: https://word-to-markdown.herokuapp.com/

[Vorlage Lastenheft.pdf](https://github.com/simonHJanssen/MoDMX/files/3079497/Vorlage.Lastenheft.pdf)

**Comment by H7orst** [comment]
[Meeting - Protokoll.docx](https://github.com/simonHJanssen/MoDMX/files/3091269/Meeting.-.Protokoll.docx)

**Comment by derElias** [comment]
Top: Projektmanagementtool Git
Diskussion: Fehlend Diagramm Zeitplanung in Git
Ergebnis: Erstellen des Diagramms in Exel. Zu Beginn für Planung mit Puffer. Am Ende zur Auswertung des Projektablaufs
Aufgaben: Erstellen des Diagramms
Termin: 25.04.

**Comment by derElias** [comment]
Top: H.1.5 Einführung
Ablauf: Einführung in Vorhandes Projekt und Features für Elias
Ergebnis:  Verständnis für vorhandene Grundlagen und Problemstellung

**Comment by derElias** [comment]
Top: Feature Liste
Ergebnis:
Absolutes Minimum:
DMX Ansteuerung per Artnet (4)
2D Rotation (4)
Filterräder,  Gobo Räder,  Lichtquellen-Farben, (16)

verschiedene Fixtures für verschiedene Channalmodi, 
(3)

(mindestens die Features umsetzen, die von den beiden Fixtures …. erfüllt werden können.)

Zeitdynamic mit scrubbarer Timeline, (100)

Relatives Minimum:
Gruppierung. d Fix. (40)
Gruppierung aus Typ (4)
Ausrichtbarkeit der Fix. auf 3D Raumpositionen (20)
Configs Speichern (12)

Jetzt wird’s gut:
Layering (32)
Gruppierung Positionen (20)
Raumtraversen Snapfunktion für Fixtures (12)
Funktionen auf Positionen (Tiefenbegrenzung für staken von Funktionen) (50)
Colormanagement (16)
Hilfe ButtonTutorial (Funktion, Wiki, Videos) (8)
(341)

Anfragen:
Personenpositionstracking?  (X)


Stretch Goals:
Parameteranimation durch Funktion beschreiben (50)
Defaulfunktion/Beispielscene (12)
MIDI-Clocks (20)
Joystick Unterstützung (12)
Gruppierung Effekte (spiegeln duplizieren…) (10+)
(445)

**Comment by derElias** [comment]
Top: Lastenheft
Ergebnis: Lastenheft wird nach Termin mit Proff Deinzer am 25.4. erstellt
Termin 25.4.

**Comment by derElias** [comment]
Top: UI-Sketch Optimierung
Diskussion: Besprechung des bisherigen UI-Sketches und notwendiger erweiterungen für weitere Features
Aufgaben: Erweiterung des UI-Sketches
Termin 25.4.
