### ISSUE TITLE
Erstellung Gannt Chart

### ISSUE THREAD

**Issue by derElias** [simonHJanssen/MoDMX#14]
Erstellung eines Gannt-charts für die Zeitliche Organisation des Projektablaufes auf Basis der Featureliste mit Afwandsschätzung

**Comment by H7orst** [comment]
Erster Entwurf:
[Gantt-Lichtsteuerung.xlsx](https://github.com/simonHJanssen/MoDMX/files/3098233/Gantt-Lichtsteuerung.xlsx)

Aufwandsabschätzung muss noch angepasst werden (Tage müssen auf Wochen gemünzt werden)
Milestones müssen noch überarbeitet werden

**Comment by H7orst** [comment]
Features Zeitrechnung:
32st. die Woche gesammte Arbeitsleitsung(für Features)?
Asolutes und Relatives Minimum: Errechneter Plantermin: 7. Juni
Jetzt wird Gut: Errechneter Plantermin: 4. Juli
Stretch Goals: Errechneter Plantermin: 1. August

**Comment by modellking** [comment]
wontfix
