### ISSUE TITLE
Feature: Anwender Doku und Doku

### ISSUE THREAD

**Issue by H7orst** [simonHJanssen/MoDMX#59]
**Describe the solution you'd like**
How to create a fixture
Create time frame entry
Group
key assignment (Traverse Drag and Drop, Mouse Scroll Wheel for Z-Axsis)
Explain menus

**Comment by H7orst** [comment]
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3609818/Projektmanagement.docx)

**Comment by H7orst** [comment]
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3610334/Projektmanagement.docx)

**Comment by H7orst** [comment]
[Problemstellung Farbenübergänge.docx](https://github.com/simonHJanssen/DMX-UI/files/3665835/Problemstellung.Farbenubergange.docx)
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3665836/Projektmanagement.docx)

**Comment by H7orst** [comment]
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3665843/Projektmanagement.docx)

**Comment by H7orst** [comment]
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3666229/Projektmanagement.docx)

**Comment by H7orst** [comment]
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3667877/Projektmanagement.docx)

**Comment by H7orst** [comment]
https://api.github.com/repos/simonHJanssen/DMX-UI/issues?state=all

**Comment by modellking** [comment]
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3669794/Projektmanagement.docx)

**Comment by derElias** [comment]
[Projektmanagement.docx](https://github.com/simonHJanssen/DMX-UI/files/3670055/Projektmanagement.docx)

**Comment by H7orst** [comment]
[Projektarbeit Dynamische Lichtshows für DMX Moving Lights.pdf](https://github.com/simonHJanssen/DMX-UI/files/3670136/Projektarbeit.Dynamische.Lichtshows.fur.DMX.Moving.Lights.pdf)

**Comment by H7orst** [comment]
[Projektarbeit Dynamische Lichtshows für DMX Moving Lights.docx](https://github.com/simonHJanssen/DMX-UI/files/3670143/Projektarbeit.Dynamische.Lichtshows.fur.DMX.Moving.Lights.docx)
